apiVersion: v1
kind: Template
labels:
  application: ${APPLICATION_NAME}
metadata:
  annotations:
    description: ${APPLICATION_NAME} route
    iconClass: icon-java
    tags: blue-green
  name: ${APPLICATION_NAME}-route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APPLICATION_NAME}-${APPLICATION_ENV}
      weight: 100
parameters:
- displayName: Application env
  name: APPLICATION_ENV
  value: blue
- displayName: Application name
  name: APPLICATION_NAME
  value: kitchensink
