# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Template
labels:
  application: kitchensink-postgres
metadata:
  annotations:
    description: Kitchensink application secret
    iconClass: icon-java
    tags: javaee,jboss,angularjs
  name: kitchensink-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}-db
  stringData:
    database-password: ${POSTGRESQL_PASSWORD}
    database-name: ${POSTGRESQL_DATABASE}
    database-user: ${POSTGRESQL_USER}
parameters:
- displayName: Application name
  name: APPLICATION_NAME
  value: ks
- displayName: Postgresql database name
  name: POSTGRESQL_DATABASE
  value: ksdatabase
- description: Username for Postgres user that will be used for accessing the database.
  displayName: Postgres Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: POSTGRESQL_USER
  required: true
- description: Password for the Postgres connection user.
  displayName: Postgres Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: POSTGRESQL_PASSWORD
  required: true
